### ISSUE TITLE
Web3Modal Issue: Login fails at homescreen

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/drecruit#10]
The web3modal for logging in fails on homescreen. The workaround is to use the /debug endpoint to login with a working web3modal. 

This could likely stem from: 

```
const init = async () => {
    const { network } = await getNetwork();
    const contract = await loadDRecruitV1Contract();
    setDRecruitContract(contract);
    const addresses = await window.ethereum.enable();
    console.log(addresses);
    const self = await SelfID.......
```

look into getNetwork(), or Scaffold

**Comment by Cali93** [comment]
Nice catch Hans getNetwork was actually the issue so I've removed it and we're relying on the Web3 context now
