### ISSUE TITLE
Add support for ERC20 token

### ISSUE THREAD

**Issue by Cali93** [moonshotcollective/drecruit#21]

**Comment by ericstlouis** [comment]
I will work on this

**Comment by QEDK** [comment]
> I will work on this

There's some more complication in this, in the sense that we want to figure out if 1 DAI is *value* or it's 1 DAI, at a basic level this is implemented as ether in the contract, so changing it to 1 ERC20 token is not valuable, so pick it up only if you want to work on the aspect of a router that works on a fixed value.

**Comment by Cali93** [comment]
I think that for the sake of simplicity it should just be 0.001 ether or 1 DAI token.
And if needed, later down the road we can add support for any ERC 20 or a router.

**Comment by Cali93** [comment]
@QEDK Can you sync with @ericstlouis to do a pair programming session to try to get this done for dogfooding ?

**Comment by QEDK** [comment]
@ericstlouis The contract part of this is trivial, let's talk more about the frontend aspect of it?

**Comment by Cali93** [comment]
@Dhaiwat10 Interested to work on this ?

**Comment by Dhaiwat10** [comment]
@Cali93 yeah I can take care of this. Had one question: by 'suppot for ERC20 tokens', do you mean that now the fees will be transferred in the form of ERC20 tokens?

**Comment by QEDK** [comment]
> @Cali93 yeah I can take care of this. Had one question: by 'suppot for ERC20 tokens', do you mean that now the fees will be transferred in the form of ERC20 tokens?

Yes. You can take a look at the contract for some idea here: #69 😏 #70 (this is the PR you can work with)

**Comment by ericstlouis** [comment]
Sorry I couldn't finish this one guys...very busy these pass few weeks

**Comment by Dhaiwat10** [comment]
@ericstlouis dont worry I've got you covered :))
