### ISSUE TITLE
Remove burner wallet

### ISSUE THREAD

**Issue by Cali93** [moonshotcollective/drecruit#28]

**Comment by Cali93** [comment]
The burner wallet doesn't have a did and there's some issue with the address that doesn't update so we might just remove the burner.

**Comment by Amirjab21** [comment]
Did a quick look - it looks like the function useUserProviderAndSigner isn't working and actually connecting to the provider properly.

I've usually seen this done with a react package like web3react/core

**Comment by Nazeeh21** [comment]
I'd like to work on this issue. 

Going through the issue description, it seems that I've to remove the burner wallet. Do I need to add anything in return?

**Comment by Cali93** [comment]
> I'd like to work on this issue.
> 
> Going through the issue description, it seems that I've to remove the burner wallet. Do I need to add anything in return?

That would be great @Nazeeh21. Yes we just need to remove the burner, nothing more.

**Comment by Nazeeh21** [comment]
Okay, sounds good. I'll soon make a PR fixing this issue.

**Comment by damianmarti** [comment]
@Cali93 I think that this issue is done https://github.com/moonshotcollective/drecruit/pull/43#issuecomment-974471001
