### ISSUE TITLE
Emoji picker

### ISSUE THREAD

**Issue by Cali93** [moonshotcollective/drecruit#31]
Emoji select input for the emoji field on the basic profile on /profile/edit-profile

**Comment by Cali93** [comment]
Emoji select input for the emoji field on the basic profile on /profile/edit-profile

**Comment by Dhaiwat10** [comment]
I can pick this one up

**Comment by Dhaiwat10** [comment]
I tried using https://www.npmjs.com/package/emoji-picker-react for this. 

Now, Next.js doesn't really like when packages want access to things like `document` or `window` on the server side. So I tried using next/dynamic (https://nextjs.org/docs/advanced-features/dynamic-import) which spat out a different sort of error.

Will investigate this further tomorrow.

**Comment by Cali93** [comment]
Ok no worries, can you try to use this one ?
https://github.com/victorias/remoji

**Comment by Dhaiwat10** [comment]
> A simpler option would be to provide a list of emojis to the select input https://chakra-ui.com/docs/form/select

Yeah I think that's a better option, actually. Going ahead with this. For now, I'll use some 5-10 random emojis. We can update the list as we need later.
