### ISSUE TITLE
Country picker

### ISSUE THREAD

**Issue by Cali93** [moonshotcollective/drecruit#35]
The residency country field in the edit-profile form should be a select field with a list of countries where the label is the name of the country and the value is the country code in [ISO_3166](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by Dhaiwat10** [comment]
Will take care of this one.

**Comment by Cali93** [comment]
Closed by https://github.com/moonshotcollective/drecruit/pull/39
