### ISSUE TITLE
Default images for the public profile

### ISSUE THREAD

**Issue by Cali93** [moonshotcollective/drecruit#37]
If the user didn't provide a pfp or a cover image, we need to display a default image.
We could use blockies for the pfp and something else for the cover image

**Comment by aserputov** [comment]
Do you need like a design for your default image or what is your idea ? I can make you something with Figma 🤔

**Comment by vyn2000** [comment]
I want to do it. Can you guide me

**Comment by Cali93** [comment]
It's up to your creativity and imagination! We could generate a cover or pfp on the fly based on their data.

**Comment by oneamanish** [comment]
see my pull req.

**Comment by Cali93** [comment]
I don't see you PR, can you send the link pls ?
For reference, we can use the fallback prop:
https://chakra-ui.com/docs/media-and-icons/image#fallback-support

**Comment by naz3eh** [comment]
I would like to give a try to this issue.

**Comment by QEDK** [comment]
This was resolved in 8b51153b118829b2c2023c8693139ad7cdb638af
